### ISSUE TITLE
Wrong due date

### ISSUE THREAD

**Issue by hinckleyc** [Allegheny-Computer-Science-203-S2020/cs203-S2020-sheets#1]
The due date on the assignment sheet is Friday the 21st by 2:30 pm.  The due date should be on Tuesday instead of Friday.

**Comment by gkapfham** [comment]
Hello @hinckleyc, thanks for raising this issue. I have fixed the problem and deployed a solution, which is now available on the course web site. I'm going to mark this issue as resolve and then close it. If you think that there are still problems related to this issue, please reopen it and provide further feedback. Thanks!
